# Site settings
title: Startup@Brown 2016
email: hello@startupatbrown.org
description: Connecting students and startups.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://startupatbrown.org" # the base hostname & protocol for your site
twitter_username: startupatbrown
github_username:  startupatbrown
port: 4444
# Build settings
markdown: kramdown
sass:
  style: compressed
